name: build-reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 22

      - name: build-src
        run: yarn build

      - name: build-app
        run: yarn package

      - name: upload-artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: packages/artifacts/
          retention-days: 1
